# Validating the YAML file:
# https://docs.travis-ci.com/user/travis-lint/

# https://docs.travis-ci.com/user/ci-environment/
sudo: false
language: java

# JDK8 is available on xenial
dist: xenial

# https://docs.travis-ci.com/user/languages/java/
jdk:
  - openjdk8
#  - openjdk10
#  - openjdk11
#  - openjdk12
#  - oraclejdk11
#  - oraclejdk12

# https://docs.travis-ci.com/user/deployment/pages/
# deploy Maven site only from master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN} # Set in travis-ci.org dashboard
  local_dir: ./target/site
  on:
    branch: master

# https://docs.travis-ci.com/user/customizing-the-build
install: mvn -B -V dependency:resolve-plugins dependency:go-offline
script: mvn clean verify site
after_failure: tail -n 500 /home/travis/build/icon-Systemhaus-GmbH/javassist-maven-plugin/target/it/projects/transform/build.log

# only the last commit is required for now
git:
  depth: 1

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
# ignore 'gh-pages' branch
branches:
  except:
  - gh-pages
