# Validating the YAML file:
# https://docs.travis-ci.com/user/travis-lint/

# https://docs.travis-ci.com/user/ci-environment/
sudo: false
language: java

# https://docs.travis-ci.com/user/languages/java/
jdk:
  - oraclejdk7

# https://docs.travis-ci.com/user/deployment/pages/
# deploy Maven site only from master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN} # Set in travis-ci.org dashboard
  local_dir: ./target/site
  on:
    branch: master

# https://docs.travis-ci.com/user/customizing-the-build
install: mvn -B -V dependency:resolve-plugins dependency:go-offline
script: mvn clean verify site
after_failure: cat /home/travis/build/stephanenicolas/javassist-maven-plugin/src/it/resources/project1/build.log

# only the last commit is required for now
git:
  depth: 1

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
# ignore 'gh-pages' branch
branches:
  except:
  - gh-pages
